// Code generated by "stringer -type=Kind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KIND_INVALID-0]
	_ = x[KIND_IDENT-1]
	_ = x[KIND_NUM_LIT-2]
	_ = x[KIND_EQUALS-3]
	_ = x[KIND_SEMICOLON-4]
	_ = x[KIND_LET-5]
}

const _Kind_name = "KIND_INVALIDKIND_IDENTKIND_NUM_LITKIND_EQUALSKIND_SEMICOLONKIND_LET"

var _Kind_index = [...]uint8{0, 12, 22, 34, 45, 59, 67}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
